burden1measdelegate: add missing #include <math.h>
fixes:

| ../../../git/zera-modules/burden1module/src/burden1measdelegate.cpp:97:35: error: 'cos' was not declared in this scope

Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>